AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''
Globals:
  Function:
    Environment:
      Variables:
        APP_STORAGE: /tmp
Resources:
  frostedmist:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: frostedmist
      Description: ''
      CodeUri: s3://frostedmist.co.uk/9ead80a8a61d941923cb4389ae294692
      Handler: public/index.php
      Timeout: 30
      MemorySize: 1024
      Runtime: provided
      Layers:
      - arn:aws:lambda:eu-west-2:209497400698:layer:php-73-fpm:4
      Events:
        GetPosts:
          Type: Api
          Properties:
            Path: /
            Method: GET
        CreatePost:
          Type: Api
          Properties:
            Path: /createPost
            Method: GET
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: GET
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: laravel-artisan
      CodeUri: s3://frostedmist.co.uk/9ead80a8a61d941923cb4389ae294692
      Handler: artisan
      Timeout: 120
      Runtime: provided
      Layers:
      - arn:aws:lambda:eu-west-2:209497400698:layer:php-72:4
      - arn:aws:lambda:eu-west-2:209497400698:layer:console:4
Outputs:
  DemoHttpApi:
    Description: URL of our function in the *Prod* environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
