AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''
Globals:
  Function:
    Environment:
      Variables:
        APP_STORAGE: /tmp
Resources:
  HomePage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: homepage
      Description: ''
      CodeUri: s3://frostedmist.co.uk/11f6aebcc62dd1f039c2f07c8296fa9f
      Handler: public/index.php
      Timeout: 30
      MemorySize: 1024
      Runtime: provided
      Layers:
      - arn:aws:lambda:eu-west-2:209497400698:layer:php-73-fpm:4
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: laravel-artisan
      CodeUri: s3://frostedmist.co.uk/11f6aebcc62dd1f039c2f07c8296fa9f
      Handler: artisan
      Timeout: 120
      Runtime: provided
      Layers:
      - arn:aws:lambda:eu-west-2:209497400698:layer:php-72:4
      - arn:aws:lambda:eu-west-2:209497400698:layer:console:4
Outputs:
  DemoHttpApi:
    Description: URL of our function in the *Prod* environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
