AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Globals:
    Function:
        Environment:
            Variables:
                # Laravel environment variables
                APP_STORAGE: '/tmp'

Resources:
    frostedmist:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'frostedmist'
            Description: ''
            CodeUri: .
            Handler: public/index.php
            Timeout: 30
            MemorySize: 1024
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:eu-west-2:209497400698:layer:php-73-fpm:4'
            Events:
                Posts:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                CreatePost:
                    Type: Api
                    Properties:
                        Path: /createPost
                        Method: ANY
                EditPost:
                    Type: Api
                    Properties:
                        Path: /editPost/{id}
                        Method: ANY
                DeletePost:
                    Type: Api
                    Properties:
                        Path: /deletePost
                        Method: ANY
                Login:
                    Type: Api
                    Properties:
                        Path: /login
                        Method: ANY
                Logout:
                    Type: Api
                    Properties:
                        Path: /logout
                        Method: ANY
    Artisan:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'laravel-artisan'
            CodeUri: .
            Handler: artisan
            Timeout: 120
            Runtime: provided
            Layers:
                # PHP runtime
                - 'arn:aws:lambda:eu-west-2:209497400698:layer:php-72:4'
                # Console layer
                - 'arn:aws:lambda:eu-west-2:209497400698:layer:console:4'

# Outputs show up in the CloudFormation dashboard
Outputs:
    DemoHttpApi:
        Description: 'URL of our function in the *Prod* environment'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
